import tkinter

m=tkinter.Tk()

m.title("VS Code Menu")

menu1 = tkinter.Menu(m)
m.config(menu=menu1)
filemenu=tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="File", menu=filemenu)
filemenu.add_command(label="New Text File")
filemenu.add_command(label="New File")
filemenu.add_command(label="New Window")
filemenu.add_command(label="New window with Profile")
filemenu.add_separator()
filemenu.add_command(label="Open File")
filemenu.add_command(label="Open Folder")
filemenu.add_command(label="Open Workspace from File")
filemenu.add_command(label="Open Recent")
filemenu.add_separator()
filemenu.add_command(label="Add Folder to Workspace...")
filemenu.add_command(label="Save Workspace As...")
filemenu.add_command(label="Duplicate Workspace")
filemenu.add_separator()
filemenu.add_command(label="Save")
filemenu.add_command(label="Save As...")
filemenu.add_command(label="Save All")
filemenu.add_separator()
filemenu.add_command(label="Share")
filemenu.add_separator()
filemenu.add_command(label="Auto Save")
filemenu.add_command(label="Preferences")
filemenu.add_separator()
filemenu.add_command(label="Revert File")
filemenu.add_command(label="Close Editor")
filemenu.add_command(label="Close Folder")
filemenu.add_command(label="Close Window")
filemenu.add_separator()
filemenu.add_command(label="Exit", command=m.destroy)

edit=tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Edit", menu=edit)
edit.add_command(label="Undo")
edit.add_command(label="Redo")
edit.add_separator()
edit.add_command(label="Cut")
edit.add_command(label="Copy")
edit.add_command(label="Paste")
edit.add_separator()
edit.add_command(label="Find")
edit.add_command(label="Replace")
edit.add_separator()
edit.add_command(label="Find in Files")
edit.add_command(label="Replace in Files")
edit.add_separator()
edit.add_command(label="Toggle Line Comment")
edit.add_command(label="Toggle Block Comment")
edit.add_command(label="Emmet: Expand Abbreviation")

selection=tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Selection", menu=selection)
selection.add_command(label="Select All")
selection.add_command(label="Expand Selection")
selection.add_command(label="Shrink Selection")
selection.add_separator()
selection.add_command(label="Copy Line Up")
selection.add_command(label="Copy Line Down")
selection.add_command(label="Move Line Up")
selection.add_command(label="Move Line Down")
selection.add_command(label="Duplicate Selection")
selection.add_separator()
selection.add_command(label="Add Cursor Above")
selection.add_command(label="Add Cursor Below")
selection.add_command(label="Add Cursor to Line Ends")
selection.add_command(label="Add Next Occurrence")
selection.add_command(label="Add Previous Occurrence")
selection.add_command(label="Select All Occurrences")
selection.add_separator()
selection.add_command(label="Switch to Ctrl+ Click for Multi-Cursor")
selection.add_command(label="Column Selection Mode")

m.geometry("400x400")
m.minsize(400, 400)
m.maxsize(400, 400)

m.mainloop()